//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StreamingUnicahEntities1 : DbContext
    {
        public StreamingUnicahEntities1()
            : base("name=StreamingUnicahEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clasificacione> Clasificaciones { get; set; }
        public DbSet<Estudio> Estudios { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<TiposPelicula> TiposPeliculas { get; set; }
    }
}
