//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public long IdPelicula { get; set; }
        public string NombrePelicula { get; set; }
        public string NombreCorto { get; set; }
        public Nullable<byte> FKIdTipoPelicula { get; set; }
        public Nullable<byte> FKIdClasificacion { get; set; }
        public Nullable<int> FKIdEstudio { get; set; }
        public Nullable<bool> Estreno { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<bool> EstadoPelicula { get; set; }
    
        public virtual Clasificaciones Clasificaciones { get; set; }
        public virtual Estudios Estudios { get; set; }
        public virtual TiposPeliculas TiposPeliculas { get; set; }
    }
}
