//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public Perfiles()
        {
            this.PerfilModulo = new HashSet<PerfilModulo>();
            this.Usuarios = new HashSet<Usuarios>();
            this.Modulos = new HashSet<Modulos>();
        }
    
        public short IdPerfil { get; set; }
        public string DescripcionPerfil { get; set; }
        public bool EstadoPerfil { get; set; }
    
        public virtual ICollection<PerfilModulo> PerfilModulo { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual ICollection<Modulos> Modulos { get; set; }
    }
}
